openapi: 3.0.3
info:
    title: Shipment Type BAPI - OpenAPI 3.0
    description: |-
        This is a OpenAPI specification of Shipment Type BAPI.
    version: 0.1.0
tags:
    - name: shipment-type
      description: Shipment Type endpoints.
security:
    - BearerAuth: []
paths:
    /shipment-types:
        parameters:
            - $ref: '#/components/parameters/ContentType'
            - $ref: '#/components/parameters/acceptLanguage'
        get:
            tags:
                - shipment-types
            summary: Shipment Types list
            description: Returns list of all Shipment Types in the system
            operationId: getShipmentTypes
            parameters:
                - $ref: '#/components/parameters/Page'
                - $ref: '#/components/parameters/Fields'
                - $ref: '#/components/parameters/Filter'
                - $ref: '#/components/parameters/Sort'
            responses:
                '200':
                    $ref: '#/components/responses/ApiShipmentTypesCollectionResponse'
                '403':
                    $ref: '#/components/responses/ApiNotAuthorizedErrorResponse'
                '4XX':
                    $ref: '#/components/responses/ApiBadRequestErrorResponse'

        post:
            tags:
                - shipment-types
            summary: Create Shipment Type
            description: Create Shipment Type
            operationId: createShipmentType
            requestBody:
                $ref: '#/components/requestBodies/ApiShipmentTypesPostRequestPayload'
            responses:
                '201':
                    $ref: '#/components/responses/ApiShipmentTypesResponse'
                '403':
                    $ref: '#/components/responses/ApiNotAuthorizedErrorResponse'
                '4XX':
                    $ref: '#/components/responses/ApiBadRequestErrorResponse'

    /shipment-types/{shipmentTypeUuid}:
        parameters:
            - name: shipmentTypeUuid
              in: path
              required: true
              description: Shipment Type UUID
              schema:
                  type: string
            - $ref: '#/components/parameters/Fields'
            - $ref: '#/components/parameters/ContentType'
            - $ref: '#/components/parameters/acceptLanguage'
        patch:
            summary: Update Shipment Type
            tags:
                - shipment-types
            requestBody:
                $ref: '#/components/requestBodies/ApiShipmentTypesPatchRequestPayload'
            operationId: updateShipmentType
            responses:
                200:
                    $ref: '#/components/responses/ApiShipmentTypesResponse'
                '403':
                    $ref: '#/components/responses/ApiNotAuthorizedErrorResponse'
                '4XX':
                    $ref: '#/components/responses/ApiBadRequestErrorResponse'

        get:
            tags:
                - shipment-types
            summary: Find Shipment Type by UUID
            description: Returns a single Shipment Type
            operationId: getShipmentTypeByUuid
            responses:
                '200':
                    $ref: '#/components/responses/ApiShipmentTypesResponse'
                '403':
                    $ref: '#/components/responses/ApiNotAuthorizedErrorResponse'
                '4XX':
                    $ref: '#/components/responses/ApiBadRequestErrorResponse'

components:
    requestBodies:
        ApiShipmentTypesPostRequestPayload:
            description: Represents create Shipment Types request
            content:
                application/vnd.api+json:
                    schema:
                        $ref: '#/components/schemas/ApiShipmentTypesPostRequest'
        ApiShipmentTypesPatchRequestPayload:
            description: Represents update Shipment Type request
            content:
                application/vnd.api+json:
                    schema:
                        $ref: '#/components/schemas/ApiShipmentTypesPatchRequest'

    responses:
        ApiShipmentTypesCollectionResponse:
            description: Listing of Shipment Types
            content:
                application/vnd.api+json:
                    schema:
                        $ref: '#/components/schemas/ApiShipmentTypesAttributesCollection'
        ApiShipmentTypesResponse:
            description: Representation of Shipment Type
            content:
                application/vnd.api+json:
                    schema:
                        $ref: '#/components/schemas/ApiShipmentTypesResponse'
        ApiNotAuthorizedErrorResponse:
            description: Not authorized
            content:
                application/vnd.api+json:
                    schema:
                        properties:
                            errors:
                                $ref: '#/components/schemas/JsonApiErrorMessageCollection'
        ApiBadRequestErrorResponse:
            description: Bad request
            content:
                application/vnd.api+json:
                    schema:
                        properties:
                            errors:
                                $ref: '#/components/schemas/JsonApiErrorMessageCollection'

    parameters:
        Page:
            name: page
            in: query
            description: 'Parameter is used to limit requested items.'
            required: false
            style: deepObject
            explode: true
            schema:
                type: object
                properties:
                    offset:
                        type: integer
                        description: 'The number of items to skip before starting to collect the result set.'
                    limit:
                        type: integer
                        description: 'The numbers of items to return.'
                example:
                    offset: 0
                    limit: 10
        Fields:
            name: fields
            in: query
            description: 'Parameter is used to extract specified items\` fields.'
            required: false
            style: deepObject
            explode: true
            schema:
                type: object
                properties:
                    resourceName:
                        type: array
                        items:
                            type: string
                        description: 'The name of resource.'
                example:
                    people: 'name,last-name'
        Filter:
            name: filter
            in: query
            description: 'Parameter is used to filter items by specified values.'
            required: false
            style: deepObject
            explode: true
            schema:
                type: object
                properties:
                    resource.propertyName:
                        description: test
                example:
                    wishlists.name: Test
                    wishlists.quantity: 1
        Sort:
            name: sort
            in: query
            description: 'Parameter is used to sort items. Use dash `-` for DESC direction.'
            required: false
            style: form
            explode: false
            schema:
                type: string
                example: -sku
        acceptLanguage:
            name: Accept-Language
            in: header
            description: 'Locale value relevant for the store.'
            required: false
            schema:
                type: string
        ContentType:
            name: Content-Type
            in: header
            description: 'Content-Type header required for all the requests.'
            required: true
            schema:
                type: string
                example: application/vnd.api+json

    schemas:
        ApiShipmentTypesAttributesCollection:
            properties:
                data:
                    type: array
                    items:
                        $ref: '#/components/schemas/ApiShipmentTypesResponseData'
        ApiShipmentTypesResponse:
            type: object
            properties:
                data:
                    $ref: '#/components/schemas/ApiShipmentTypesResponseData'
        ApiShipmentTypesResponseData:
            type: object
            properties:
                type:
                    type: string
                    example: shipment-types
                id:
                    type: string
                    format: uuid
                    example: 518409fa-a5c2-4b52-8ac9-a382ebdc6084
                attributes:
                    $ref: '#/components/schemas/ApiShipmentTypesAttributes'
                links:
                    $ref: '#/components/schemas/ApiLinks'
        ApiShipmentTypesPostRequest:
            type: object
            properties:
                data:
                    $ref: '#/components/schemas/ApiShipmentTypesPostRequestData'
        ApiShipmentTypesPatchRequest:
            type: object
            properties:
                data:
                    $ref: '#/components/schemas/ApiShipmentTypesPatchRequestData'
        ApiShipmentTypesPostRequestData:
            type: object
            properties:
                type:
                    type: string
                    example: shipment-types
                attributes:
                    $ref: '#/components/schemas/ApiShipmentTypesPostRequestAttributes'
        ApiShipmentTypesPatchRequestData:
            type: object
            properties:
                type:
                    type: string
                    example: shipment-types
                id:
                    type: string
                    format: uuid
                    example: 518409fa-a5c2-4b52-8ac9-a382ebdc6084
                attributes:
                    $ref: '#/components/schemas/ApiShipmentTypesPatchRequestAttributes'
        ApiShipmentTypesPostRequestAttributes:
            required:
                - name
                - key
                - isActive
                - stores
            type: object
            properties:
                name:
                    type: string
                    example: My Shipment Type
                key:
                    type: string
                    example: my_shipment_type
                isActive:
                    type: boolean
                    example: true
                stores:
                    type: array
                    items:
                        type: string
                    example:
                        - DE
                        - AT
        ApiShipmentTypesPatchRequestAttributes:
            type: object
            properties:
                name:
                    type: string
                    example: My Shipment Type
                isActive:
                    type: boolean
                    example: true
                key:
                    type: string
                    example: my_shipment_type
                stores:
                    type: array
                    items:
                        type: string
                    example:
                        - DE
                        - AT
        ApiShipmentTypesAttributes:
            type: object
            properties:
                name:
                    type: string
                    example: My Shipment Type
                key:
                    type: string
                    example: my_shipment_type
                isActive:
                    type: boolean
                    example: true
                stores:
                    type: array
                    items:
                        type: string
                    example:
                        - DE
                        - AT
        ApiLinks:
            properties:
                self:
                    type: string
        JsonApiErrorMessageCollection:
            type: array
            items:
                $ref: '#/components/schemas/JsonApiErrorMessage'
        JsonApiErrorMessage:
            type: object
            properties:
                status:
                    type: integer
                code:
                    type: string
                message:
                    type: string
